tests: fix missing wait in TLS test suite
TLS test suite setup was missing call to `wait_containers_ready` that
other test suites utilize. It sometimes caused the tests to error out
with:

error: too early for operation, device not yet seeded or device model
not acknowledged

Signed-off-by: Martin Kalcok <martin.kalcok@canonical.com>
Signed-off-by: Theodoros Vakalopoulos <theovakalopoulos@gmail.com>